# This file is auto-generated from the current state of the database. Instead
# of editing this file, please use the migrations feature of Active Record to
# incrementally modify your database, and then regenerate this schema definition.
#
# Note that this schema.rb definition is the authoritative source for your
# database schema. If you need to create the application database on another
# system, you should be using db:schema:load, not running all the migrations
# from scratch. The latter is a flawed and unsustainable approach (the more migrations
# you'll amass, the slower it'll run and the greater likelihood for issues).
#
# It's strongly recommended that you check this file into your version control system.

ActiveRecord::Schema.define(version: 20171023173153) do

  create_table "bencostshares", force: :cascade do |t|
    t.text     "BusinessYear"
    t.text     "StateCode"
    t.text     "IssuerId"
    t.text     "SourceName"
    t.text     "VersionNum"
    t.datetime "ImportDate"
    t.text     "IssuerId2"
    t.text     "StateCode2"
    t.text     "StandardComponentId"
    t.text     "PlanId"
    t.text     "BenefitName"
    t.text     "CopayInnTier1"
    t.text     "CopayInnTier2"
    t.text     "CopayOutofNet"
    t.text     "CoinsInnTier1"
    t.text     "CoinsInnTier2"
    t.text     "CoinsOutofNet"
    t.text     "IsEHB"
    t.text     "IsStateMandate"
    t.text     "IsCovered"
    t.text     "QuantLimitOnSvc"
    t.text     "LimitQty"
    t.text     "LimitUnit"
    t.text     "MinimumStay"
    t.text     "Exclusions"
    t.text     "Explanation"
    t.text     "EHBVarReason"
    t.text     "IsSubjtoDedTier1"
    t.text     "IsSubjtoDedTier2"
    t.text     "IsExclFromInnMOOP"
    t.text     "IsExclFromOonMOOP"
    t.text     "RowNumber"
    t.datetime "created_at",          null: false
    t.datetime "updated_at",          null: false
    t.index ["PlanId"], name: "index_bencostshares_on_PlanID", limit: 255
    t.index ["StandardComponentId"], name: "index_bencostshares_on_StandardComponentID", limit: 255
  end

  create_table "businessrules", force: :cascade do |t|
    t.text     "BusinessYear"
    t.text     "StateCode"
    t.text     "IssuerId"
    t.text     "SourceName"
    t.text     "VersionNum"
    t.datetime "ImportDate"
    t.text     "IssuerId2"
    t.text     "TIN"
    t.text     "ProductId"
    t.text     "StandardComponentId"
    t.text     "EnrolleeContractRateDeterminationRule"
    t.text     "TwoParentFamilyMaxDependentsRule"
    t.text     "SingleParentFamilyMaxDependentsRule"
    t.text     "DependentMaximumAgRule"
    t.text     "ChildrenOnlyContractMaxChildrenRule"
    t.text     "DomesticPartnerAsSpouseIndicator"
    t.text     "SameSexPartnerAsSpouseIndicator"
    t.text     "AgeDeterminationRule"
    t.text     "MinimumTobaccoFreeMonthsRule"
    t.text     "CohabitationRule"
    t.text     "RowNumber"
    t.text     "MarketCoverage"
    t.text     "DentalOnlyPlan"
    t.datetime "created_at",                            null: false
    t.datetime "updated_at",                            null: false
    t.index ["StandardComponentId"], name: "index_businessrules_on_StandardComponentID", limit: 255
    t.index ["TIN"], name: "index_businessrules_on_TIN", limit: 255
  end

  create_table "crosswalks", force: :cascade do |t|
    t.text     "State"
    t.text     "DentalPlan"
    t.text     "PlanID_2016"
    t.text     "IssuerID_2016"
    t.text     "MultistatePlan_2016"
    t.text     "MetalLevel_2016"
    t.text     "ChildAdultOnly_2016"
    t.text     "FIPSCode"
    t.text     "ZipCode"
    t.text     "CrosswalkLevel"
    t.text     "ReasonForCrosswalk"
    t.text     "PlanID_2017"
    t.text     "IssuerID_2017"
    t.text     "MultistatePlan_2017"
    t.text     "MetalLevel_2017"
    t.text     "ChildAdultOnly_2017"
    t.text     "AgeOffPlanID_2017"
    t.text     "IssuerID_AgeOff2017"
    t.text     "MultistatePlan_AgeOff2017"
    t.text     "MetalLevel_AgeOff2017"
    t.text     "ChildAdultOnly_AgeOff2017"
    t.datetime "created_at",                null: false
    t.datetime "updated_at",                null: false
    t.index ["PlanID_2017"], name: "index_crosswalks_on_PlanID_2017", limit: 255
  end

  create_table "networks", force: :cascade do |t|
    t.text     "BusinessYear"
    t.text     "StateCode"
    t.text     "IssuerId"
    t.text     "SourceName"
    t.datetime "ImportDate"
    t.text     "NetworkName"
    t.text     "NetworkId"
    t.text     "NetworkURL"
    t.text     "MarketCoverage"
    t.text     "DentalOnlyPlan"
    t.datetime "created_at",     null: false
    t.datetime "updated_at",     null: false
  end

  create_table "plans", force: :cascade do |t|
    t.text     "BusinessYear"
    t.text     "StateCode"
    t.text     "IssuerId"
    t.text     "SourceName"
    t.text     "VersionNum"
    t.datetime "ImportDate"
    t.text     "BenefitPackageId"
    t.text     "IssuerId2"
    t.text     "StateCode2"
    t.text     "MarketCoverage"
    t.text     "DentalOnlyPlan"
    t.text     "TIN"
    t.text     "StandardComponentId"
    t.text     "PlanMarketingName"
    t.text     "HIOSProductId"
    t.text     "HPID"
    t.text     "NetworkId"
    t.text     "ServiceAreaId"
    t.text     "FormularyId"
    t.text     "IsNewPlan"
    t.text     "PlanType"
    t.text     "MetalLevel"
    t.text     "DesignType"
    t.text     "UniquePlanDesign"
    t.text     "QHPNonQHPTypeId"
    t.text     "IsNoticeRequiredForPregnancy"
    t.text     "IsReferralRequiredForSpecialist"
    t.text     "SpecialistRequiringReferral"
    t.text     "PlanLevelExclusions"
    t.text     "IndianPlanVariationEstimatedAdvancedPaymentAmountPerEnrollee"
    t.text     "CompositeRatingOffered"
    t.text     "ChildOnlyOffering"
    t.text     "ChildOnlyPlanId"
    t.text     "WellnessProgramOffered"
    t.text     "DiseaseManagementProgramsOffered"
    t.text     "EHBPercentTotalPremium"
    t.text     "EHBPediatricDentalApportionmentQuantity"
    t.text     "IsGuaranteedRate"
    t.date     "PlanEffictiveDate"
    t.date     "PlanExpirationDate"
    t.text     "OutOfCountryCoverage"
    t.text     "OutOfCountryCoverageDescription"
    t.text     "OutOfServiceAreaCoverage"
    t.text     "OutOfServiceAreaCoverageDescription"
    t.text     "NationalNetwork"
    t.text     "URLForEnrollmentPayment"
    t.text     "FormularyURL"
    t.text     "PlanId"
    t.text     "PlanVariantMarketingName"
    t.text     "CSRVariationType"
    t.text     "IssuerActuarialValue"
    t.text     "AVCalculatorOutputNumber"
    t.text     "MedicalDrugDeductiblesIntegrated"
    t.text     "MedicalDrugMaximumOutofPocketIntegrated"
    t.text     "MultipleInNetworkTiers"
    t.text     "FirstTierUtilization"
    t.text     "SecondTierUtilization"
    t.text     "SBCHavingaBabyDeductible"
    t.text     "SBCHavingaBabyCopayment"
    t.text     "SBCHavingaBabyCoinsurance"
    t.text     "SBCHavingaBabyLimit"
    t.text     "SBCHavingDiabetesDeductible"
    t.text     "SBCHavingDiabetesCopayment"
    t.text     "SBCHavingDiabetesCoinsurance"
    t.text     "SBCHavingDiabetesLimit"
    t.text     "SBCHavingSimplefractureDeductible"
    t.text     "SBCHavingSimplefractureCopayment"
    t.text     "SBCHavingSimplefractureCoinsurance"
    t.text     "SBCHavingSimplefractureLimit"
    t.text     "SpecialtyDrugMaximumCoinsurance"
    t.text     "InpatientCopaymentMaximumDays"
    t.text     "BeginPrimaryCareCostSharingAfterNumberOfVisits"
    t.text     "BeginPrimaryCareDeductibleCoinsuranceAfterNumberOfCopays"
    t.text     "MEHBInnTier1IndividualMOOP"
    t.text     "MEHBInnTier1FamilyPerPersonMOOP"
    t.text     "MEHBInnTier1FamilyPerGroupMOOP"
    t.text     "MEHBInnTier2IndividualMOOP"
    t.text     "MEHBInnTier2FamilyPerPersonMOOP"
    t.text     "MEHBInnTier2FamilyPerGroupMOOP"
    t.text     "MEHBOutOfNetIndividualMOOP"
    t.text     "MEHBOutOfNetFamilyPerPersonMOOP"
    t.text     "MEHBOutOfNetFamilyPerGroupMOOP"
    t.text     "MEHBCombInnOonIndividualMOOP"
    t.text     "MEHBCombInnOonFamilyPerPersonMOOP"
    t.text     "MEHBCombInnOonFamilyPerGroupMOOP"
    t.text     "DEHBInnTier1IndividualMOOP"
    t.text     "DEHBInnTier1FamilyPerPersonMOOP"
    t.text     "DEHBInnTier1FamilyPerGroupMOOP"
    t.text     "DEHBInnTier2IndividualMOOP"
    t.text     "DEHBInnTier2FamilyPerPersonMOOP"
    t.text     "DEHBInnTier2FamilyPerGroupMOOP"
    t.text     "DEHBOutOfNetIndividualMOOP"
    t.text     "DEHBOutOfNetFamilyPerPersonMOOP"
    t.text     "DEHBOutOfNetFamilyPerGroupMOOP"
    t.text     "DEHBCombInnOonIndividualMOOP"
    t.text     "DEHBCombInnOonFamilyPerPersonMOOP"
    t.text     "DEHBCombInnOonFamilyPerGroupMOOP"
    t.text     "TEHBInnTier1IndividualMOOP"
    t.text     "TEHBInnTier1FamilyPerPersonMOOP"
    t.text     "TEHBInnTier1FamilyPerGroupMOOP"
    t.text     "TEHBInnTier2IndividualMOOP"
    t.text     "TEHBInnTier2FamilyPerPersonMOOP"
    t.text     "TEHBInnTier2FamilyPerGroupMOOP"
    t.text     "TEHBOutOfNetIndividualMOOP"
    t.text     "TEHBOutOfNetFamilyPerPersonMOOP"
    t.text     "TEHBOutOfNetFamilyPerGroupMOOP"
    t.text     "TEHBCombInnOonIndividualMOOP"
    t.text     "TEHBCombInnOonFamilyPerPersonMOOP"
    t.text     "TEHBCombInnOonFamilyPerGroupMOOP"
    t.text     "MEHBDedInnTier1Individual"
    t.text     "MEHBDedInnTier1FamilyPerPerson"
    t.text     "MEHBDedInnTier1FamilyPerGroup"
    t.text     "MEHBDedInnTier1Coinsurance"
    t.text     "MEHBDedInnTier2Individual"
    t.text     "MEHBDedInnTier2FamilyPerPerson"
    t.text     "MEHBDedInnTier2FamilyPerGroup"
    t.text     "MEHBDedInnTier2Coinsurance"
    t.text     "MEHBDedOutOfNetIndividual"
    t.text     "MEHBDedOutOfNetFamilyPerPerson"
    t.text     "MEHBDedOutOfNetFamilyPerGroup"
    t.text     "MEHBDedCombInnOonIndividual"
    t.text     "MEHBDedCombInnOonFamilyPerPerson"
    t.text     "MEHBDedCombInnOonFamilyPerGroup"
    t.text     "DEHBDedInnTier1Individual"
    t.text     "DEHBDedInnTier1FamilyPerPerson"
    t.text     "DEHBDedInnTier1FamilyPerGroup"
    t.text     "DEHBDedInnTier1Coinsurance"
    t.text     "DEHBDedInnTier2Individual"
    t.text     "DEHBDedInnTier2FamilyPerPerson"
    t.text     "DEHBDedInnTier2FamilyPerGroup"
    t.text     "DEHBDedInnTier2Coinsurance"
    t.text     "DEHBDedOutOfNetIndividual"
    t.text     "DEHBDedOutOfNetFamilyPerPerson"
    t.text     "DEHBDedOutOfNetFamilyPerGroup"
    t.text     "DEHBDedCombInnOonIndividual"
    t.text     "DEHBDedCombInnOonFamilyPerPerson"
    t.text     "DEHBDedCombInnOonFamilyPerGroup"
    t.text     "TEHBDedInnTier1Individual"
    t.text     "TEHBDedInnTier1FamilyPerPerson"
    t.text     "TEHBDedInnTier1FamilyPerGroup"
    t.text     "TEHBDedInnTier1Coinsurance"
    t.text     "TEHBDedInnTier2Individual"
    t.text     "TEHBDedInnTier2FamilyPerPerson"
    t.text     "TEHBDedInnTier2FamilyPerGroup"
    t.text     "TEHBDedInnTier2Coinsurance"
    t.text     "TEHBDedOutOfNetIndividual"
    t.text     "TEHBDedOutOfNetFamilyPerPerson"
    t.text     "TEHBDedOutOfNetFamilyPerGroup"
    t.text     "TEHBDedCombInnOonIndividual"
    t.text     "TEHBDedCombInnOonFamilyPerPerson"
    t.text     "TEHBDedCombInnOonFamilyPerGroup"
    t.text     "IsHSAEligible"
    t.text     "HSAOrHRAEmployerContribution"
    t.text     "HSAOrHRAEmployerContributionAmount"
    t.text     "URLForSummaryofBenefitsCoverage"
    t.text     "PlanBrochure"
    t.text     "RowNumber"
    t.datetime "created_at",                                                   null: false
    t.datetime "updated_at",                                                   null: false
    t.index ["NetworkId"], name: "index_plans_on_NetworkId", limit: 255
  end

  create_table "qualities", force: :cascade do |t|
    t.text     "IssuerID"
    t.text     "PlanID"
    t.text     "GlobalRatingValue"
    t.text     "EnrolleeExperienceRatingValue"
    t.text     "PlanEfficiencyAffordabilityManagementRatingValue"
    t.text     "ClinicalQualityManagementRatingValue"
    t.text     "NotRatedReason_GlobalRatingDesc"
    t.text     "NotRatedReason_EnrolleeExperienceRatingDesc"
    t.text     "NotRatedReason_PlanEfficiencyAffordabilityManagementRatingDesc"
    t.text     "NotRatedReason_ClinicalQualityManagementRatingDesc"
    t.datetime "created_at",                                                     null: false
    t.datetime "updated_at",                                                     null: false
    t.index ["PlanID"], name: "index_qualities_on_PlanID", limit: 255
  end

  create_table "rates", force: :cascade do |t|
    t.text     "BusinessYear"
    t.text     "StateCode"
    t.text     "IssuerId"
    t.text     "SourceName"
    t.text     "VersionNum"
    t.datetime "ImportDate"
    t.text     "IssuerId2"
    t.text     "FederalTIN"
    t.date     "RateEffectiveDate"
    t.date     "RateExpirationDate"
    t.text     "PlanId"
    t.text     "RatingAreaId"
    t.text     "Tobacco"
    t.text     "Age"
    t.text     "IndividualRate"
    t.text     "IndividualTobaccoRate"
    t.text     "Couple"
    t.text     "PrimarySubscriberAndOneDependent"
    t.text     "PrimarySubscriberAndTwoDependents"
    t.text     "PrimarySubscriberAndThreeOrMoreDependents"
    t.text     "CoupleAndOneDependent"
    t.text     "CoupleAndTwoDependents"
    t.text     "CoupleAndThreeOrMoreDependents"
    t.text     "RowNumber"
    t.datetime "created_at",                                null: false
    t.datetime "updated_at",                                null: false
    t.index ["FederalTIN"], name: "index_rates_on_FederalTIN", limit: 255
    t.index ["PlanId"], name: "index_rates_on_PlanID", limit: 255
  end

  create_table "serviceareas", force: :cascade do |t|
    t.text     "BusinessYear"
    t.text     "StateCode"
    t.text     "IssuerId"
    t.text     "SourceName"
    t.datetime "ImportDate"
    t.text     "ServiceAreaId"
    t.text     "ServiceAreaName"
    t.text     "CoverEntireState"
    t.text     "County"
    t.text     "PartialCounty"
    t.text     "ZipCodes"
    t.text     "PartialCountyJustification"
    t.text     "MarketCoverage"
    t.text     "DentalOnlyPlan"
    t.datetime "created_at",                 null: false
    t.datetime "updated_at",                 null: false
  end

  create_table "transparencies", force: :cascade do |t|
    t.text     "State"
    t.text     "IssuerName"
    t.text     "IssuerID"
    t.text     "IssuerDBAIfApplicable"
    t.text     "URLClaimsPolicies"
    t.text     "NumberOfClaims2015"
    t.text     "NumberOfClaimsDenials"
    t.text     "NumberOfInternalAppealsFiled"
    t.text     "NumberOfInternalAppealsOverturned"
    t.text     "PercentOfInternalAppealsOverturned"
    t.text     "NumberOfExternalAppealsFiled"
    t.text     "NumberOfExternalAppealsOverturned"
    t.text     "PercentOfExternalAppealsOverturned"
    t.text     "FinancialInformation"
    t.text     "EnrollmentData"
    t.text     "DisenrollmentData"
    t.datetime "created_at",                         null: false
    t.datetime "updated_at",                         null: false
  end

  create_table "zipmappings", force: :cascade do |t|
    t.string   "FULLZIP"
    t.string   "ZIP"
    t.string   "STATE_CODE"
    t.string   "COUNTY"
    t.float    "RES_RATIO"
    t.float    "BUS_RATIO"
    t.float    "OTH_RATIO"
    t.float    "TOT_RATIO"
    t.string   "COUNTY_NAME"
    t.string   "RATING_AREA"
    t.datetime "created_at",  null: false
    t.datetime "updated_at",  null: false
  end

end
