class CreatePlans < ActiveRecord::Migration[5.0]
  def change
    create_table :plans do |t|
      t.text :BusinessYear
      t.text :StateCode
      t.text :IssuerId
      t.text :SourceName
      t.text :VersionNum
      t.datetime :ImportDate
      t.text :BenefitPackageId
      t.text :IssuerId2
      t.text :StateCode2
      t.text :MarketCoverage
      t.text :DentalOnlyPlan
      t.text :TIN
      t.text :StandardComponentId
      t.text :PlanMarketingName
      t.text :HIOSProductId
      t.text :HPID
      t.text :NetworkId
      t.text :ServiceAreaId
      t.text :FormularyId
      t.text :IsNewPlan
      t.text :PlanType
      t.text :MetalLevel
      t.text :DesignType
      t.text :UniquePlanDesign
      t.text :QHPNonQHPTypeId
      t.text :IsNoticeRequiredForPregnancy
      t.text :IsReferralRequiredForSpecialist
      t.text :SpecialistRequiringReferral
      t.text :PlanLevelExclusions
      t.text :IndianPlanVariationEstimatedAdvancedPaymentAmountPerEnrollee
      t.text :CompositeRatingOffered
      t.text :ChildOnlyOffering
      t.text :ChildOnlyPlanId
      t.text :WellnessProgramOffered
      t.text :DiseaseManagementProgramsOffered
      t.text :EHBPercentTotalPremium
      t.text :EHBPediatricDentalApportionmentQuantity
      t.text :IsGuaranteedRate
      t.date :PlanEffictiveDate
      t.date :PlanExpirationDate
      t.text :OutOfCountryCoverage
      t.text :OutOfCountryCoverageDescription
      t.text :OutOfServiceAreaCoverage
      t.text :OutOfServiceAreaCoverageDescription
      t.text :NationalNetwork
      t.text :URLForEnrollmentPayment
      t.text :FormularyURL
      t.text :PlanId
      t.text :PlanVariantMarketingName
      t.text :CSRVariationType
      t.text :IssuerActuarialValue
      t.text :AVCalculatorOutputNumber
      t.text :MedicalDrugDeductiblesIntegrated
      t.text :MedicalDrugMaximumOutofPocketIntegrated
      t.text :MultipleInNetworkTiers
      t.text :FirstTierUtilization
      t.text :SecondTierUtilization
      t.text :SBCHavingaBabyDeductible
      t.text :SBCHavingaBabyCopayment
      t.text :SBCHavingaBabyCoinsurance
      t.text :SBCHavingaBabyLimit
      t.text :SBCHavingDiabetesDeductible
      t.text :SBCHavingDiabetesCopayment
      t.text :SBCHavingDiabetesCoinsurance
      t.text :SBCHavingDiabetesLimit
      t.text :SBCHavingSimplefractureDeductible
      t.text :SBCHavingSimplefractureCopayment
      t.text :SBCHavingSimplefractureCoinsurance
      t.text :SBCHavingSimplefractureLimit
      t.text :SpecialtyDrugMaximumCoinsurance
      t.text :InpatientCopaymentMaximumDays
      t.text :BeginPrimaryCareCostSharingAfterNumberOfVisits
      t.text :BeginPrimaryCareDeductibleCoinsuranceAfterNumberOfCopays
      t.text :MEHBInnTier1IndividualMOOP
      t.text :MEHBInnTier1FamilyPerPersonMOOP
      t.text :MEHBInnTier1FamilyPerGroupMOOP
      t.text :MEHBInnTier2IndividualMOOP
      t.text :MEHBInnTier2FamilyPerPersonMOOP
      t.text :MEHBInnTier2FamilyPerGroupMOOP
      t.text :MEHBOutOfNetIndividualMOOP
      t.text :MEHBOutOfNetFamilyPerPersonMOOP
      t.text :MEHBOutOfNetFamilyPerGroupMOOP
      t.text :MEHBCombInnOonIndividualMOOP
      t.text :MEHBCombInnOonFamilyPerPersonMOOP
      t.text :MEHBCombInnOonFamilyPerGroupMOOP
      t.text :DEHBInnTier1IndividualMOOP
      t.text :DEHBInnTier1FamilyPerPersonMOOP
      t.text :DEHBInnTier1FamilyPerGroupMOOP
      t.text :DEHBInnTier2IndividualMOOP
      t.text :DEHBInnTier2FamilyPerPersonMOOP
      t.text :DEHBInnTier2FamilyPerGroupMOOP
      t.text :DEHBOutOfNetIndividualMOOP
      t.text :DEHBOutOfNetFamilyPerPersonMOOP
      t.text :DEHBOutOfNetFamilyPerGroupMOOP
      t.text :DEHBCombInnOonIndividualMOOP
      t.text :DEHBCombInnOonFamilyPerPersonMOOP
      t.text :DEHBCombInnOonFamilyPerGroupMOOP
      t.text :TEHBInnTier1IndividualMOOP
      t.text :TEHBInnTier1FamilyPerPersonMOOP
      t.text :TEHBInnTier1FamilyPerGroupMOOP
      t.text :TEHBInnTier2IndividualMOOP
      t.text :TEHBInnTier2FamilyPerPersonMOOP
      t.text :TEHBInnTier2FamilyPerGroupMOOP
      t.text :TEHBOutOfNetIndividualMOOP
      t.text :TEHBOutOfNetFamilyPerPersonMOOP
      t.text :TEHBOutOfNetFamilyPerGroupMOOP
      t.text :TEHBCombInnOonIndividualMOOP
      t.text :TEHBCombInnOonFamilyPerPersonMOOP
      t.text :TEHBCombInnOonFamilyPerGroupMOOP
      t.text :MEHBDedInnTier1Individual
      t.text :MEHBDedInnTier1FamilyPerPerson
      t.text :MEHBDedInnTier1FamilyPerGroup
      t.text :MEHBDedInnTier1Coinsurance
      t.text :MEHBDedInnTier2Individual
      t.text :MEHBDedInnTier2FamilyPerPerson
      t.text :MEHBDedInnTier2FamilyPerGroup
      t.text :MEHBDedInnTier2Coinsurance
      t.text :MEHBDedOutOfNetIndividual
      t.text :MEHBDedOutOfNetFamilyPerPerson
      t.text :MEHBDedOutOfNetFamilyPerGroup
      t.text :MEHBDedCombInnOonIndividual
      t.text :MEHBDedCombInnOonFamilyPerPerson
      t.text :MEHBDedCombInnOonFamilyPerGroup
      t.text :DEHBDedInnTier1Individual
      t.text :DEHBDedInnTier1FamilyPerPerson
      t.text :DEHBDedInnTier1FamilyPerGroup
      t.text :DEHBDedInnTier1Coinsurance
      t.text :DEHBDedInnTier2Individual
      t.text :DEHBDedInnTier2FamilyPerPerson
      t.text :DEHBDedInnTier2FamilyPerGroup
      t.text :DEHBDedInnTier2Coinsurance
      t.text :DEHBDedOutOfNetIndividual
      t.text :DEHBDedOutOfNetFamilyPerPerson
      t.text :DEHBDedOutOfNetFamilyPerGroup
      t.text :DEHBDedCombInnOonIndividual
      t.text :DEHBDedCombInnOonFamilyPerPerson
      t.text :DEHBDedCombInnOonFamilyPerGroup
      t.text :TEHBDedInnTier1Individual
      t.text :TEHBDedInnTier1FamilyPerPerson
      t.text :TEHBDedInnTier1FamilyPerGroup
      t.text :TEHBDedInnTier1Coinsurance
      t.text :TEHBDedInnTier2Individual
      t.text :TEHBDedInnTier2FamilyPerPerson
      t.text :TEHBDedInnTier2FamilyPerGroup
      t.text :TEHBDedInnTier2Coinsurance
      t.text :TEHBDedOutOfNetIndividual
      t.text :TEHBDedOutOfNetFamilyPerPerson
      t.text :TEHBDedOutOfNetFamilyPerGroup
      t.text :TEHBDedCombInnOonIndividual
      t.text :TEHBDedCombInnOonFamilyPerPerson
      t.text :TEHBDedCombInnOonFamilyPerGroup
      t.text :IsHSAEligible
      t.text :HSAOrHRAEmployerContribution
      t.text :HSAOrHRAEmployerContributionAmount
      t.text :URLForSummaryofBenefitsCoverage
      t.text :PlanBrochure
      t.text :RowNumber

      t.timestamps
    end
    
    add_index :plans, :NetworkId, :length => 255
    add_foreign_key :plans, :networks, :length => 255
    
  end
end
